services:
  backend:
    build:
      context: ./myproject
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "5678:5678"  # Port cho debugpy
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DEBUG=${DEBUG:-false}  # Thêm biến môi trường DEBUG
    depends_on:
      - redis
      - db
    volumes:
      - ./myproject:/app
    env_file:
      - ./myproject/.env
    command: >
      sh -c "python manage.py migrate &&
             if [ \"$${DEBUG}\" = \"true\" ]; then
               python -m debugpy --listen 0.0.0.0:5678 --wait-for-client manage.py runserver 0.0.0.0:8000;
             else
               gunicorn --bind 0.0.0.0:8000 myproject.wsgi:application;
             fi"

  db:
    image: postgres:13
    container_name: postgres-db
    env_file:
      - ./myproject/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./front_end
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./front_end:/app

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"

  celery:
    build:
      context: ./myproject
      dockerfile: Dockerfile
    command: celery -A myproject worker --loglevel=info
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    env_file:
      - ./myproject/.env

  celery-beat:
    build:
      context: ./myproject
      dockerfile: Dockerfile
    command: celery -A myproject beat --loglevel=info
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    env_file:
      - ./myproject/.env

volumes:
  postgres_data: