# Generated by Django 4.2.20 on 2025-04-27 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_transaction_date'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dailyrecord',
            index=models.Index(fields=['user', 'date'], name='accounts_da_user_id_70a2e5_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyrecord',
            index=models.Index(fields=['date'], name='accounts_da_date_31d656_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['daily_record', 'type'], name='accounts_tr_daily_r_a40a63_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['type', 'category'], name='accounts_tr_type_a5db8f_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['date'], name='accounts_tr_date_4ebe57_idx'),
        ),
    ]
